"""add_system_settings_retry

Revision ID: 4489d4180af6
Revises: 5d385d1f088d
Create Date: 2026-01-28 08:24:16.765887

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4489d4180af6"
down_revision: Union[str, Sequence[str], None] = "5d385d1f088d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artist_splits")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist_splits",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("original_artist", sa.VARCHAR(), nullable=False),
        sa.Column("split_part", sa.VARCHAR(), nullable=False),
        sa.Column("is_primary", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
