"""Add Identity Resolution models

Revision ID: 5d385d1f088d
Revises: cfc31820018f
Create Date: 2026-01-27 08:52:10.629053

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d385d1f088d"
down_revision: Union[str, Sequence[str], None] = "cfc31820018f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotent checks
    from sqlalchemy.engine.reflection import Inspector

    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if "artist_aliases" not in tables:
        op.create_table(
            "artist_aliases",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("raw_name", sa.String(), nullable=False),
            sa.Column("resolved_name", sa.String(), nullable=True),
            sa.Column("is_verified", sa.Boolean(), nullable=False),
            sa.Column("is_null", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_artist_aliases_raw_name"),
            "artist_aliases",
            ["raw_name"],
            unique=True,
        )

    if "artist_splits" not in tables:
        op.create_table(
            "artist_splits",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("original_artist", sa.String(), nullable=False),
            sa.Column("split_part", sa.String(), nullable=False),
            sa.Column("is_primary", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )

    if "proposed_splits" not in tables:
        op.create_table(
            "proposed_splits",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("original_artist", sa.String(), nullable=False),
            sa.Column("split_parts", sa.JSON(), nullable=False),
            sa.Column("status", sa.String(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_proposed_splits_original_artist"),
            "proposed_splits",
            ["original_artist"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_proposed_splits_raw_artist"), table_name="proposed_splits"
    )
    op.drop_table("proposed_splits")
    op.drop_index(
        op.f("ix_artist_aliases_raw_name"), table_name="artist_aliases"
    )
    op.drop_table("artist_aliases")
    # ### end Alembic commands ###
