"""Add DiscoveryQueue and is_verified

Revision ID: a43de339102a
Revises: 4489d4180af6
Create Date: 2026-02-04 09:35:29.691762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a43de339102a'
down_revision: Union[str, Sequence[str], None] = '4489d4180af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=True)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('callsign', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callsign')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_title'), 'albums', ['title'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('is_instrumental', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_title'), 'works', ['title'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('version_type', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('isrc', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_isrc'), 'recordings', ['isrc'], unique=False)
    op.create_index(op.f('ix_recordings_title'), 'recordings', ['title'], unique=False)
    op.create_table('work_artists',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('work_id', 'artist_id')
    )
    op.create_table('broadcast_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('raw_artist', sa.String(), nullable=False),
    sa.Column('raw_title', sa.String(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('match_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_broadcast_station_time', 'broadcast_logs', ['station_id', 'played_at'], unique=False)
    op.create_index(op.f('ix_broadcast_logs_played_at'), 'broadcast_logs', ['played_at'], unique=False)
    op.create_index(op.f('ix_broadcast_logs_recording_id'), 'broadcast_logs', ['recording_id'], unique=False)
    op.create_table('discovery_queue',
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('raw_artist', sa.String(), nullable=False),
    sa.Column('raw_title', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('suggested_recording_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suggested_recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('signature')
    )
    op.create_table('identity_bridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_signature', sa.String(), nullable=False),
    sa.Column('reference_artist', sa.String(), nullable=False),
    sa.Column('reference_title', sa.String(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_bridge_log_signature'), 'identity_bridge', ['log_signature'], unique=True)
    op.create_table('library_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_files_file_hash'), 'library_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_library_files_path'), 'library_files', ['path'], unique=True)
    op.add_column('proposed_splits', sa.Column('raw_artist', sa.String(), nullable=False))
    op.add_column('proposed_splits', sa.Column('proposed_artists', sa.JSON(), nullable=False))
    op.add_column('proposed_splits', sa.Column('confidence', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_proposed_splits_original_artist'), table_name='proposed_splits')
    op.create_index(op.f('ix_proposed_splits_raw_artist'), 'proposed_splits', ['raw_artist'], unique=True)
    op.drop_column('proposed_splits', 'original_artist')
    op.drop_column('proposed_splits', 'split_parts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposed_splits', sa.Column('split_parts', sqlite.JSON(), nullable=False))
    op.add_column('proposed_splits', sa.Column('original_artist', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_proposed_splits_raw_artist'), table_name='proposed_splits')
    op.create_index(op.f('ix_proposed_splits_original_artist'), 'proposed_splits', ['original_artist'], unique=False)
    op.drop_column('proposed_splits', 'confidence')
    op.drop_column('proposed_splits', 'proposed_artists')
    op.drop_column('proposed_splits', 'raw_artist')
    op.drop_index(op.f('ix_library_files_path'), table_name='library_files')
    op.drop_index(op.f('ix_library_files_file_hash'), table_name='library_files')
    op.drop_table('library_files')
    op.drop_index(op.f('ix_identity_bridge_log_signature'), table_name='identity_bridge')
    op.drop_table('identity_bridge')
    op.drop_table('discovery_queue')
    op.drop_index(op.f('ix_broadcast_logs_recording_id'), table_name='broadcast_logs')
    op.drop_index(op.f('ix_broadcast_logs_played_at'), table_name='broadcast_logs')
    op.drop_index('idx_broadcast_station_time', table_name='broadcast_logs')
    op.drop_table('broadcast_logs')
    op.drop_table('work_artists')
    op.drop_index(op.f('ix_recordings_title'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_isrc'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_works_title'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_albums_title'), table_name='albums')
    op.drop_table('albums')
    op.drop_table('system_settings')
    op.drop_table('stations')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
