"""add_match_reason

Revision ID: cfc31820018f
Revises:
Create Date: 2026-01-26 19:55:41.275232

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfc31820018f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Logic commented out because column exists and inspect check is flaky
    pass
    # if 'match_reason' not in columns:
    #    op.add_column('broadcast_logs', sa.Column('match_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("broadcast_logs", "match_reason")
    # ### end Alembic commands ###
